### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by pratbhoir** [Kir4Kun/ha-miraie-ac#5]
Hi @Kir4Kun , 

My AC is not connecting. I am getting this below issue.

2023-06-01 13:36:48.810 ERROR (Thread-9 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
  File "/config/.local/lib/python3.10/site-packages/miraie_ac/broker.py", line 46, in on_disconnect
    asyncio.create_task(self.on_get_token(cb))
  File "/usr/lib/python3.10/asyncio/tasks.py", line 336, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop

Let me know, If I am doing something wrong.

**Comment by Kir4Kun** [comment]
Fixed now.
